language: objective-c
osx_image: xcode7.1
xcode_project: tvtest.xcodeproj
xcode_scheme: tvtest
xcode_sdk: appletvsimulator9.0

matrix:
  include:
    - osx_image: xcode6.4
    - osx_image: xcode7

cache: cocoapods

script:
  - xcodebuild -workspace tvtest.xcworkspace -scheme tvtest -sdk appletvsimulator9.0 build test
